language: go
go:
- 1.13.x
install:
- "./prifi.sh install"
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- make all
after_success:
- goveralls -coverprofile=profile.cov -service=travis-ci -repotoken $COVERALLS_TOKEN
notifications:
  email: false
