Simulation = "PriFi"
Servers=5
Bf = 100
Rounds = 10
CloseWait = 6000
NTrustees = 2
CellSizeUp = 1000
CellSizeDown = 10000
RelayWindowSize = 10
RelayUseDummyDataDown = false
RelayReportingLimit = -1
UseUDP = false
DoLatencyTests = true

Hosts
5