Description = "Prifi"

[[servers]]
  Address = "tcp://127.0.0.1:6000"
  Public = "tn9jVNLOkkzbECbpGJC0Gl0q94Gl3XF62eBleBrovic="
  Description = "client"

[[servers]]
  Address = "tcp://127.0.0.1:6001"
  Public = "jcH+mPRM6V66I/YHZ2L6ejIGWrD1OtGB7v7K3Js7aqs="
  Description = "client"

[[servers]]
  Address = "tcp://127.0.0.1:6002"
  Public = "WrqywNxZtEznMC+mwK6HtbPb/RksVpDKIjVB9OF8at8="
  Description = "client"

[[servers]]
  Address = "tcp://127.0.0.1:7000"
  Public = "VYcxFJhJcfOLY/esG1Gr20Lnc+HkKm73v3YsEx7jRds="
  Description = "relay"

[[servers]]
  Address = "tcp://127.0.0.1:7001"
  Public = "iwjdlBd0kAlOviatMvTuN95cB0am9mY8+DmeK86c3Fg="
  Description = "trustee"

[[servers]]
  Address = "tcp://127.0.0.1:7002"
  Public = "fte323V5gLtAzZRrwgzEIBQBDbrTlpeqk02A69Mgr3g="
  Description = "trustee"
