[[hosts]]
  ID = 0
  IP = "10.0.1.254"

[[hosts]]
  ID = 1
  IP = "10.1.0.1"

[[hosts]]
  ID = 2
  IP = "10.1.0.2"

[[hosts]]
  ID = 3
  IP = "10.1.0.3"

[[hosts]]
  ID = 4
  IP = "10.0.1.1"

[[hosts]]
  ID = 5
  IP = "10.0.1.2"

[[hosts]]
  ID = 6
  IP = "10.0.1.3"

[[hosts]]
  ID = 7
  IP = "10.0.1.4"

[[hosts]]
  ID = 8
  IP = "10.0.1.5"

[[hosts]]
  ID = 9
  IP = "10.0.1.1"

[[hosts]]
  ID = 10
  IP = "10.0.1.2"

[[hosts]]
  ID = 11
  IP = "10.0.1.3"

[[hosts]]
  ID = 12
  IP = "10.0.1.4"

[[hosts]]
  ID = 13
  IP = "10.0.1.5"
