[[hosts]]
  Name = "client-0.LB-LLD.SAFER.deterlab.net"
  IP = "10.1.0.1"

[[hosts]]
  Name = "client-1.LB-LLD.SAFER.deterlab.net"
  IP = "10.1.0.2"

[[hosts]]
  Name = "client-2.LB-LLD.SAFER.deterlab.net"
  IP = "10.1.0.3"

[[hosts]]
  Name = "client-3.LB-LLD.SAFER.deterlab.net"
  IP = "10.1.0.4"

[[hosts]]
  Name = "client-4.LB-LLD.SAFER.deterlab.net"
  IP = "10.1.0.5"

[[hosts]]
  Name = "client-5.LB-LLD.SAFER.deterlab.net"
  IP = "10.1.0.6"

[[hosts]]
  Name = "client-6.LB-LLD.SAFER.deterlab.net"
  IP = "10.1.0.7"

[[hosts]]
  Name = "client-7.LB-LLD.SAFER.deterlab.net"
  IP = "10.1.0.8"

[[hosts]]
  Name = "client-8.LB-LLD.SAFER.deterlab.net"
  IP = "10.1.0.9"

[[hosts]]
  Name = "client-9.LB-LLD.SAFER.deterlab.net"
  IP = "10.1.0.10"

[[hosts]]
  Name = "relay.LB-LLD.SAFER.deterlab.net"
  IP = "10.1.0.254"
  IP2 = "10.0.1.254"

[[hosts]]
  Name = "trustee-0.LB-LLD.SAFER.deterlab.net"
  IP = "10.0.1.1"

[[hosts]]
  Name = "trustee-1.LB-LLD.SAFER.deterlab.net"
  IP = "10.0.1.2"

[[hosts]]
  Name = "trustee-2.LB-LLD.SAFER.deterlab.net"
  IP = "10.0.1.3"

[[hosts]]
  Name = "trustee-3.LB-LLD.SAFER.deterlab.net"
  IP = "10.0.1.4"

[[hosts]]
  Name = "trustee-4.LB-LLD.SAFER.deterlab.net"
  IP = "10.0.1.5"
