Simulation = "PriFi"
Servers = 10
Depth = 1
Rounds = 1
CloseWait = 6000
NTrustees = 3
CellSizeUp = 100
CellSizeDown = 1000
RelayWindowSize = 10
RelayUseDummyDataDown = false
RelayReportingLimit = -1
RelayDataOutputEnabled = true
ClientDataOutputEnabled = true
UseUDP = false
DoLatencyTests = true
SocksServerPort = 8080
SocksClientPort = 8090

Hosts
4
5