Simulation = "PriFi"
Servers = 14
Depth = 1
CloseWait = 10000000
RunWait = 10000000
NTrustees = 3
CellSizeUp = 100
CellSizeDown = 140
RelayWindowSize = 1
OverrideLogLevel = 3
ForceConsoleColor = true
RelayUseDummyDataDown = true
RelayReportingLimit = 10000
RelayDataOutputEnabled = true
ClientDataOutputEnabled = true
UseUDP = true
DoLatencyTests = true
SocksServerPort = 8080
SocksClientPort = 8090
TrusteeIPRegexPattern = "10\\.1\\.0\\.([0-9]+)"
ClientIPRegexPattern = "10\\.0\\.1\\.([0-9]+)"
RelayIPRegexPattern = "10\\.([0-9]+)\\.([0-9]+)\\.254"
Hosts = 14

Rounds
1
