Simulation = "PriFi"
Servers = 9
Depth = 1
CloseWait = 10000000
RunWait = 10000000
NTrustees = 3
CellSizeUp = 7000
CellSizeDown = 17500
RelayWindowSize = 5
DCNetType = "Simple"
OverrideLogLevel = 3
ForceConsoleColor = true
RelayUseOpenClosedSlots = true
RelayUseDummyDataDown = false
RelayReportingLimit = 100000
RelayDataOutputEnabled = true
ClientDataOutputEnabled = false
UseUDP = true
DoLatencyTests = false
SocksServerPort = 8080
SocksClientPort = 8090
TrusteeIPRegexPattern = "10\\.1\\.0\\.([0-9]+)"
ClientIPRegexPattern = "10\\.0\\.1\\.([0-9]+)"
RelayIPRegexPattern = "10\\.([0-9]+)\\.([0-9]+)\\.254"
Hosts = 94
ReplayPCAP = true
PCAPFolder = "pcaps/"
SimulDelayBetweenClients = 0
DisruptionProtectionEnabled = false
OpenClosedSlotsMinDelayBetweenRequests = 0
TrusteeNeverSlowDown = true

Rounds
1
