Simulation = "PriFi"
Servers = 9
Depth = 1
Rounds = 10
CloseWait = 10000000
RunWait = 10000000
NTrustees = 3
CellSizeUp = 100
CellSizeDown = 1000
RelayWindowSize = 10
OverrideLogLevel = 1
ForceConsoleColor = true
RelayUseDummyDataDown = false
RelayReportingLimit = 10000
RelayDataOutputEnabled = true
ClientDataOutputEnabled = true
UseUDP = false
DoLatencyTests = true
SocksServerPort = 8080
SocksClientPort = 8090
TrusteeIPRegexPattern = "10\\.1\\.0\\.([0-9]+)"
ClientIPRegexPattern = "10\\.0\\.1\\.([0-9]+)"
RelayIPRegexPattern = "10\\.([0-9]+)\\.([0-9]+)\\.254"

Hosts
5
9
14