Simulation = "PriFi"
Servers = 9
Depth = 1
Rounds = 10
CloseWait = 6000
NTrustees = 3
CellSizeUp = 100
CellSizeDown = 1000
RelayWindowSize = 10
OverrideLogLevel = 1
ForceConsoleColor = true
RelayUseDummyDataDown = false
RelayReportingLimit = 10000
RelayDataOutputEnabled = true
ClientDataOutputEnabled = true
UseUDP = false
DoLatencyTests = true
SocksServerPort = 8080
SocksClientPort = 8090

Hosts
5
9
14