Hosts = 14
CellSizeUp = 500
CellSizeDown = 17500
RelayWindowSize = 4
DCNetType = "Simple"
RelayReportingLimit = 100000
RelayMaxNumberOfConsecutiveFailedRounds = 3
RelayProcessingLoopSleepTime = 0
RelayRoundTimeOut = 1000
RelayTrusteeCacheLowBound = 1000
RelayTrusteeCacheHighBound = 1500
RelayUseDummyDataDown = true
RelayDataOutputEnabled = true
ClientDataOutputEnabled = false
UseUDP = false
DoLatencyTests = false
ReplayPCAP = false
PCAPFolder = "pcap/"
DisruptionProtectionEnabled = false
RelayUseOpenClosedSlots = false
OpenClosedSlotsMinDelayBetweenRequests = 0
TrusteeSleepTimeBetweenMessages = 100
TrusteeAlwaysSlowDown = false
TrusteeNeverSlowDown = true
SocksServerPort = 8080
SocksClientPort = 8090
TrusteeIPRegexPattern = "10\\.1\\.0\\.([0-9]+)"
ClientIPRegexPattern = "10\\.0\\.1\\.([0-9]+)"
RelayIPRegexPattern = "10\\.([0-9]+)\\.([0-9]+)\\.254"
OverrideLogLevel = 1
ForceConsoleColor = true
Simulation = "PriFi"
Servers = 9
Depth = 1
CloseWait = 10000000
RunWait = 10000000
NTrustees = 3
SimulDelayBetweenClients = 0

Rounds
1
