Simulation = "PriFi"
Servers = 9
Depth = 1
CloseWait = 10000000
RunWait = 10000000
NTrustees = 3
CellSizeUp = x
CellSizeDown = 17500
RelayWindowSize = 3
DCNetType = "Simple"
OverrideLogLevel = 1
ForceConsoleColor = true
RelayUseOpenClosedSlots = true
RelayUseDummyDataDown = true
RelayReportingLimit = 10000
RelayDataOutputEnabled = true
ClientDataOutputEnabled = false
UseUDP = true
DoLatencyTests = false
SocksServerPort = 8080
SocksClientPort = 8090
TrusteeIPRegexPattern = "10\\.1\\.0\\.([0-9]+)"
ClientIPRegexPattern = "10\\.0\\.1\\.([0-9]+)"
RelayIPRegexPattern = "10\\.([0-9]+)\\.([0-9]+)\\.254"
Hosts = 15
ReplayPCAP = true
PCAPFolder = "pcap/"
SimulDelayBetweenClients = 0
DisruptionProtectionEnabled = false
OpenClosedSlotsMinDelayBetweenRequests = 0

Rounds
1
