[[servers]]
  Name = "relay.LB-LLD.SAFER.isi.deterlab.net"
  IP = "10.1.0.254"
  IP2 = "10.0.1.254"

[[servers]]
  Name = "trustee-0.LB-LLD.SAFER.isi.deterlab.net"
  IP = "10.1.0.1"

[[servers]]
  Name = "trustee-1.LB-LLD.SAFER.isi.deterlab.net"
  IP = "10.1.0.2"

[[servers]]
  Name = "trustee-2.LB-LLD.SAFER.isi.deterlab.net"
  IP = "10.1.0.3"

[[servers]]
  Name = "client-0.LB-LLD.SAFER.isi.deterlab.net"
  IP = "10.0.1.1"

[[servers]]
  Name = "client-1.LB-LLD.SAFER.isi.deterlab.net"
  IP = "10.0.1.2"

[[servers]]
  Name = "client-2.LB-LLD.SAFER.isi.deterlab.net"
  IP = "10.0.1.3"

[[servers]]
  Name = "client-3.LB-LLD.SAFER.isi.deterlab.net"
  IP = "10.0.1.4"

[[servers]]
  Name = "client-4.LB-LLD.SAFER.isi.deterlab.net"
  IP = "10.0.1.5"