NTrustees = 3
CellSizeUp = 5000
CellSizeDown = 17500
RelayWindowSize = 1
DCNetType = "Simple"
OverrideLogLevel = 3
ForceConsoleColor = true
RelayUseOpenClosedSlots = true
RelayUseDummyDataDown = true
RelayReportingLimit = 10000
RelayDataOutputEnabled = true
ClientDataOutputEnabled = true
UseUDP = false
DoLatencyTests = true
SocksServerPort = 8080
SocksClientPort = 8090
TrusteeIPRegexPattern = "10\\.1\\.0\\.([0-9]+)"
ClientIPRegexPattern = "10\\.0\\.1\\.([0-9]+)"
RelayIPRegexPattern = "10\\.([0-9]+)\\.([0-9]+)\\.254"
Hosts = 19
ReplayPCAP = false
PCAPFolder = "pcap/"
SimulDelayBetweenClients = 0
DisruptionProtectionEnabled = false
OpenClosedSlotsMinDelayBetweenRequests = 1000