CellSizeUp = 2000
CellSizeDown = 1000
RelayWindowSize = 10
RelayUseDummyDataDown = false
RelayReportingLimit = -1
RelayDataOutputEnabled = true
RelayUseOpenClosedSlots = false
ClientDataOutputEnabled = true
UseUDP = false
DoLatencyTests = true
SocksServerPort = 8080
SocksClientPort = 8090
OverrideLogLevel = 1
ForceConsoleColor = false
DCNetType = "Simple"
ReplayPCAP = true
PCAPFolder = "pcap/"
TrusteeNeverSlowDown = true
DisruptionProtectionEnabled = true
