CellSizeUp = 1000
CellSizeDown = 1000
RelayWindowSize = 1
RelayUseDummyDataDown = false
RelayReportingLimit = -1
RelayDataOutputEnabled = true
RelayUseOpenClosedSlots = false
ClientDataOutputEnabled = true
UseUDP = false
DoLatencyTests = true
SocksServerPort = 8080
SocksClientPort = 8090
OverrideLogLevel = 3
ForceConsoleColor = false
DCNetType = "Simple"
ReplayPCAP = true
PCAPFolder = "pcap/"
TrusteeNeverSlowDown = true