CellSizeUp = 5000
CellSizeDown = 17500
RelayWindowSize = 5
DCNetType = "Simple"
OverrideLogLevel = 2
ForceConsoleColor = true
RelayUseOpenClosedSlots = true
RelayUseDummyDataDown = false
RelayReportingLimit = -1
RelayDataOutputEnabled = true
ClientDataOutputEnabled = true
UseUDP = false
DoLatencyTests = true
SocksServerPort = 8080
SocksClientPort = 8090
TrusteeIPRegexPattern = "10\\.1\\.0\\.([0-9]+)"
ClientIPRegexPattern = "10\\.0\\.1\\.([0-9]+)"
RelayIPRegexPattern = "10\\.([0-9]+)\\.([0-9]+)\\.254"
ReplayPCAP = false
PCAPFolder = "pcap/"
SimulDelayBetweenClients = 0
DisruptionProtectionEnabled = false
OpenClosedSlotsMinDelayBetweenRequests = 100
TrusteeSleepTimeBetweenMessages = 100
TrusteeAlwaysSlowDown = false
TrusteeNeverSlowDown = false
RelayMaxNumberOfConsecutiveFailedRounds = 3
RelayProcessingLoopSleepTime = 0
RelayRoundTimeOut = 1000
RelayTrusteeCacheLowBound = 10
RelayTrusteeCacheHighBound = 15
EquivocationProtectionEnabled = true