CellSizeUp = 100
CellSizeDown = 1000
RelayWindowSize = 1
RelayUseDummyDataDown = false
RelayReportingLimit = -1
RelayDataOutputEnabled = true
ClientDataOutputEnabled = true
UseUDP = false
DoLatencyTests = true
SocksServerPort = 8080
SocksClientPort = 8090
OverrideLogLevel = -1
ForceConsoleColor = false
