CellSizeUp = 5000
CellSizeDown = 5000
RelayWindowSize = 1
DCNetType = "Simple"
RelayUseDummyDataDown = false
RelayDataOutputEnabled = true
ClientDataOutputEnabled = true
UseUDP = false
DoLatencyTests = false
ReplayPCAP = false
PCAPFolder = "pcap/"
DisruptionProtectionEnabled = false
RelayUseOpenClosedSlots = true
OpenClosedSlotsMinDelayBetweenRequests = 1000
TrusteeSleepTimeBetweenMessages = 1000
TrusteeAlwaysSlowDown = true
TrusteeNeverSlowDown = false
OverrideLogLevel = -1
ForceConsoleColor = true
RelayReportingLimit = -1
SocksServerPort = 8080
SocksClientPort = 8090
TrusteeIPRegexPattern = "10\\.1\\.0\\.([0-9]+)"
ClientIPRegexPattern = "10\\.0\\.1\\.([0-9]+)"
RelayIPRegexPattern = "10\\.([0-9]+)\\.([0-9]+)\\.254"
SimulDelayBetweenClients = 0
RelayMaxNumberOfConsecutiveFailedRounds = 3
RelayProcessingLoopSleepTime = 1000
RelayRoundTimeOut = 0
RelayTrusteeCacheLowBound = 10
RelayTrusteeCacheHighBound = 15